pages:
  stage: deploy
  script:
    # Generate the html files in the director "public"
    - (mkdir public ; cd cmucl-www/www; emacs -batch -q -l ../build.el -f wb-make)
    # Create tarball
    - mkdir public/mirror
    - (cd public; tar cjf mirror/cmucl-site.tar.bz2 .)
  artifacts:
     paths:
       - public
  tags:
    - site-gen
