pages:
  stage: deploy
  script:
    # Generate the html files in the director "public"
    - (mkdir public ; cd cmucl-www/www; emacs -batch -q -l ../build.el -f wb-make)
    # Create tarball
    - (cd public; tar cf ../cmucl-site.tar .)
    - mkdir public/mirror
    - (cd public/mirror; tar xf ../../cmucl-site.tar)
  artifacts:
     paths:
       - public
  tags:
    - site-gen
