pages:
  stage: deploy
  script:
    # Get dev version of texinfo
    - git clone https://git.savannah.gnu.org/git/texinfo.git
    - cd texinfo
    - ./autogen.sh
    - ./configure --prefix=$PWD/..
    - make; make install
    - cd ..
    - mkdir public
    - PATH=$PWD/bin:$PATH
    - export TEXINPUTS=$PWD/docs:$TEXINPUTS
    - ls bin
    - type -all makeinfo; makeinfo --version
    - type -all texindex; texindex --version
    # Generate the website.  Touch build-el.force to force building.
    # I think we should always build everything even if only one file changed.
    - touch /tmp/build-el-force
    - (cd cmucl-www/www; emacs -batch -q -l ../build.el -f wb-make)
    # Generate the design doc.
    - (cd docs/internals; make all)
    # Generate the user manual.  Include info, pdf, and html versions.
    - (cd docs/cmu-user; make all)
    # Generate the hemlock manuals.
    - (cd docs/interface; make all)
    # Copy everything to the appropriate subdirectories
    - (cd docs/internals; make install)
    - (cd docs/cmu-user; make install)
    - (cd docs/interface; make install)
  artifacts:
     paths:
       - public
  tags:
    - site-gen
