pages:
  stage: deploy
  script:
    - mkdir public
    # Generate the website.  Touch build-el.force to force building.
    # I think we should always build everything even if only one file changed.
    - touch /tmp/build-el-force
    - (cd cmucl-www/www; emacs -batch -q -l ../build.el -f wb-make)
    # Generate the design doc.
    - (cd docs/internals; makeinfo --info design.texi)
    - (cd docs/internals; makeinfo --pdf design.texi)
    - (cd docs/internals; makeinfo --html design.texi)
    # Generate the user manual.  Include info, pdf, and html versions.
    - (cd docs/cmu-user; makeinfo --info cmu-user.texi)
    - (cd docs/cmu-user; makeinfo --pdf cmu-user.texi)
    - (cd docs/cmu-user; makeinfo - --html cmu-user.texi)
    # Generate the hemlock manuals.
    - (cd docs/interface; makeinfo --info toolkit.texi; makeinfo --info internals.texi)
    - (cd docs/interface; makeinfo --pdf toolkit.texi; makeinfo --pdf internals.texi)
    - (cd docs/interface; makeinfo --html toolkit.texi; makeinfo --html internals.texi)
    # Copy everything to the appropriate subdirectories
    - mkdir -p public/docs/internals public/docs/internals/html
    - cp -r docs/internals/design.info* public/docs/internals/
    - cp -r docs/internals/design/* public/docs/internals/html
    - cp -r docs/internals/design.pdf public/docs/internals/
    - mkdir -p public/docs/cmu-user public/docs/cmu-user/html
    - cp -r docs/cmu-user/cmu-user.info* public/docs/cmu-user/
    - cp -r docs/cmu-user/cmu-user/* public/docs/cmu-user/html
    - cp -r docs/cmu-user/cmu-user.pdf public/docs/cmu-user
    - mkdir -p public/docs/interface public/docs/interface/toolkit/html public/docs/interface/internals/html
    - cp -r docs/interface/toolkit.info* public/docs/interface/
    - cp -r docs/interface/toolkit/* public/docs/interface/toolkit/html
    - cp -r docs/interface/toolkit.pdf public/docs/interface
    - cp -r docs/interface/internals.info* public/docs/interface/
    - cp -r docs/interface/internals/* public/docs/interface/internals/html
    - cp -r docs/interface/internals.pdf public/docs/interface
  artifacts:
     paths:
       - public
  tags:
    - site-gen
