<hr noshade>
<img border=0 src="http://validator.w3.org/images/vh40.gif"
     align="right" alt="" height=31 width=88>

<font size="-1" face="Helvetica, Arial">
Last modified @@DATE@@ by &lt;webmaster@cmucl.cons.org&gt; <br>
Copyright &copy; 1999-2010 CMUCL Project <br>
Validate
<a href="http://validator.w3.org/checklink?uri=@@URL@@">links</a>,
<a href="http://validator.w3.org/check?uri=@@URL@@">HTML</a>,
<a href="http://jigsaw.w3.org/css-validator/validator?uri=@@BASE@@cmucl.css">stylesheet</a>.
</font>
<a href="https://plus.google.com/111360785690907674471?prsrc=3" style="text-decoration: none;"><img src="https://ssl.gstatic.com/images/icons/gplus-16.png" width="16" height="16" style="border: 0;"/></a>

