<hr noshade>
		
<p>
  <a href="http://validator.w3.org/check?uri=referer">
  <img src="http://www.w3.org/Icons/valid-html40" alt="Valid HTML 4.0 Transitional" height="31" width="88">
  </a>
</p>
<!-- Google translate -->		
<div id="google_translate_element"></div><script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({
    pageLanguage: 'en'
  }, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<br>		
<font size="-1" face="Helvetica, Arial">
Last modified @@DATE@@ by &lt;webmaster@cmucl.cons.org&gt; <br>
Copyright &copy; 1999-2019 CMUCL Project <br>
Validate
<a href="https://validator.w3.org/checklink?uri=@@URL@@">links</a>,
<a href="https://validator.w3.org/check?uri=@@URL@@">HTML</a>,
<a href="https://jigsaw.w3.org/css-validator/validator?uri=@@BASE@@cmucl.css">stylesheet</a>.
</font>

<br>
