<hr noshade>
		
<img border=0 src="http://validator.w3.org/images/vh40.gif"
     align="right" alt="" height=31 width=88>
<!-- Render the Google +1 badge -->
<g:plusone annotation="inline" href="https://plus.google.com/111360785690907674471/"></g:plusone>
<!-- Render the Google g+ badge -->	
<a href="https://plus.google.com/111360785690907674471?prsrc=3" style="cursor:pointer;display:inline-block;text-decoration:none;color:#333;font:13px/16px arial,sans-serif;"><span style="display:inline-block;font-weight:bold;vertical-align:top;margin-right:5px;margin-top:8px;">CMUCL</span><span style="display:inline-block;vertical-align:top;margin-right:15px;margin-top:8px;">on</span><img src="https://ssl.gstatic.com/images/icons/gplus-32.png" alt="" style="border:0;width:32px;height:32px;"/></a>		

<!-- Google translate -->		
<div id="google_translate_element"></div><script>
function googleTranslateElementInit() {
  new google.translate.TranslateElement({
    pageLanguage: 'en'
  }, 'google_translate_element');
}
</script><script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

<br>		
<font size="-1" face="Helvetica, Arial">
Last modified @@DATE@@ by &lt;webmaster@cmucl.cons.org&gt; <br>
Copyright &copy; 1999-2010 CMUCL Project <br>
Validate
<a href="http://validator.w3.org/checklink?uri=@@URL@@">links</a>,
<a href="http://validator.w3.org/check?uri=@@URL@@">HTML</a>,
<a href="http://jigsaw.w3.org/css-validator/validator?uri=@@BASE@@cmucl.css">stylesheet</a>.
</font>

<br>
