<meta name="author" content="CMUCL webmasters">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="Content-Language" content="en-US">
<link rev="made" href="mailto:webmaster@cmucl.cons.org" title="CMUCL feedback">
<link rel="stylesheet" href="@@HOME@@cmucl.css" type="text/css">
<link rel="home" href="@@HOME@@index.html" title="CMUCL Home Page">
<link rel="banner" href="@@HOME@@doc/" title="Documentation">
<link rel="banner" href="@@HOME@@credits.html" title="Credits">
<link rel="banner" href="@@HOME@@download.html" title="Download">
<link rel="banner" href="@@HOME@@projects.html" title="Projects">
<link rel="banner" href="@@HOME@@ports.html" title="Ports">
<link rel="banner" href="@@HOME@@support.html" title="Support">

<!-- For Google analytics -->		
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18172365-1']);
  _gaq.push(['_setDomainName', 'none']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
