\input texinfo
@settitle CMUCL User's Manual

@fonttextsize 10

@titlepage
@title Design of CMU Common Lisp
@subtitle January 15, 2003
@subtitle 21c
@author Robert A. MacLachlan, @i{ed}
@end titlepage

@c \trnumber{CMU-CS-91-???}

@c Some common abbreviations
@macro cmucl {}
@sc{cmucl}
@end macro

@macro hspace {arg}
@end macro

@contents

@ifnottex
@node Top
@top Design of CMU Common Lisp
@end ifnottex

@center @b{Abstract}

This report documents internal details of the CMU Common Lisp
compiler and run-time system.  CMU Common Lisp is a public domain
implementation of Common Lisp that runs on various Unix workstations.
This document is a work in progress: neither the contents nor the
presentation are completed. Nevertheless, it provides some useful
background information, in particular regarding the @cmucl{} compiler.

@c This was created by hand.  Don't let the tools do this for you!
@menu
* Package and File Structure::
* System Building::
* Compiler Overview::
* The Implicit Continuation Representation::
* ICR conversion::
* Local call analysis::
* Find components::
* ICR optimize::
* Type checking::
* Constraint propagation::
* ICR finalize::
* Environment analysis::
* Virtual Machine Representation Introduction::
* Global TN assignment::
* Local TN assignment::
* Control optimization::
* VMR conversion::
* Copy propagation::
* Representation selection::
* Lifetime analysis::
* Packing::
* Code generation::
* Assembly::
* Dumping::
* User Interface of the Compiler::
* Retargeting the Compiler::
* Storage bases and classes::
* Type system parameterization::
* VOP Definition::
* Assembler Retargeting::
* Writing Assembly Code::
* Required VOPS::
* Standard Primitives::
* Customizing VMR Conversion::
* The Type System::
* The Info Database::
* The IR1 Interpreter::
* Debugger::
* Debugger Information::
* Object Format::
* Memory Management::
* Interface to C and Assembler::
* Low-level debugging::
* Core File Format::
* Fasload File Format::
* Appendix::
* Glossary::

@end menu

@include architecture.texi
@include compiler.texi
@include retargeting.texi
@include run-time.texi
@node Appendix
@appendix @asis{}
@include glossary.texi

@bye

@c Local Variables:
@c mode: texinfo
@c TeX-master: t
@c End:
