\input texinfo
@settitle CMUCL User's Manual

@macro cmucl {}
@sc{CMUCL}
@end macro

@macro clisp {}
Common Lisp
@end macro

@macro llisp {}
Common Lisp
@end macro

@macro hemlock {}
Hemlock
@end macro

@macro python {}
Python
@end macro

@macro credits {arg}
@center @b{\arg\}
@end macro

@macro dash {}
---
@end macro

@macro false {}
@code{nil}
@end macro

@macro nil {}
@code{nil}
@end macro

@macro true {}
@code{t}
@end macro

@macro kwd {keyword}
@code{:\keyword\}
@end macro

@macro cltl {}
@i{Common Lisp: The Language}
@end macro

@macro cltltwo {}
@i{Common Lisp: The Language II}
@end macro

@macro amprest {}
&rest
@end macro

@macro ampoptional {}
@code{&optional}
@end macro

@macro tindexed {arg}
@code{\arg\}
@end macro

@macro findexed {arg}
@code{\arg\}
@end macro

@macro vindexed {arg}
@code{\arg\}
@end macro

@macro funref {arg}
@code{\arg\}
@end macro

@macro args {arg}
\arg\
@end macro

@macro mopt {arg}
@{\arg\@}
@end macro

@rmacro mstar {arg}
@{\arg\@}*
@end rmacro

@macro mplus {arg}
@{\arg\@}+
@end macro

@macro mor {}
|
@end macro

@macro mgroup {arg}
@{@var{\arg\}@}
@end macro
@macro keys {arg}
&key \arg\
@end macro

@macro varref {arg}
@code{\arg\}
@end macro

@macro macref {arg}
@code{\arg\}
@end macro

@titlepage
@title CMUCL User's Manual
@subtitle October 2017
@subtitle 21c
@author Robert A. MacLachlan, @i{Editor}

@iftex
@vskip 10pt
@end iftex
@quotation
@cmucl{} is a free, high-performance implementation of the Common Lisp
programming language, which runs on most major Unix platforms. It
mainly conforms to the ANSI Common Lisp Standard. @cmucl{} features a
sophisticated native-code compiler, a foreign function interface, a
graphical source-level debugger, an interface to the X11 Window
System, and an Emacs-like editor.

@iftex
@vskip 5pt
@end iftex
@b{Keywords}: lisp, Common Lisp, manual, compiler, programming
language implementation, programming environment
@end quotation

@end titlepage

@contents

@ifnottex
@node Top
@top CMUCL User's Manual
@end ifnottex

@include introduction.texi
@c @include extensions.texi
@include debugger.texi
@include compiler.texi
@include compiler-hint.texi
@bye
